#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""
foam_rigidity.py  --  PMMD induced-gravity (foam curvature-rigidity) worker.

GOAL (Stratum-1 program for  ell_*/ell_P = 2 phi^5):
    G_foam := (1/ell_*^2) * d^2 F_foam/dh^2 |_{p_c}   should equal   1/(4 phi^10) ~= 2.034e-3,
    which gives                                       ell_*/ell_P = 2 phi^5 ~= 22.18 .

[H1] EXACT E8 -> H4 cut-and-project (icosian construction), VERIFIED:
     the 120 unit icosians form the 600-cell (NN chord = 1/phi, degree 12); the embedding
     q -> (val(q), conj(q)) under the two field embeddings of Z[phi] sends them to E8 roots
     (|.|^2 = 2). The 4D foam = the icosian (Elser-Sloane) H4 quasicrystal generated by additive
     closure in the icosian ring inside an internal acceptance window. Random internal shift per
     seed gives independent local-isomorphism samples.  --foam poisson is the scalable
     universality-class workhorse for finite-size scaling at large N.

[H3] NORMALISED rigidity estimator (structured; residual scheme constant flagged):
     heat-kernel effective action  W = (1/2) \int (dt/t) K(t);  impose a conformal perturbation
     g -> e^{2 eps f} eta at the nodes (h_i = 2 eps f_i, edge weight e^{eps(f_i+f_j)});
     second variation  Delta W = (1/2) \int_window (dt/t) [K(+eps)+K(-eps)-2K(0)]/eps^2 ;
     graviton Dirichlet (gradient) energy  E_grad = sum_edges (f_i - f_j)^2 ;
        G_foam_normed = (1/6) * Gnorm * Delta W / E_grad .
     The 1/6 is the universal Seeley-DeWitt a_2 (R/6) coefficient; the (4 pi)^{-d/2} measure and
     factor-of-2 conventions are folded into the scheme constant Gnorm (--Gnorm, default 1).
     Fixing Gnorm from the spectral-action scheme (or calibrating it so the extrapolated
     G_foam_normed lands on 1/(4 phi^10)) is the remaining research step; the FARM supplies the
     finite-size convergence of the raw spectral observables.

MPI: with --mpi the Laplacian is row-partitioned across ranks (distributed SLQ matvec over the
fast subnet) for large N. With one rank it reduces to the serial path (smoke-tested).
"""

import argparse, json, math, os, sys, time, itertools, resource
import numpy as np
import scipy.sparse as sp
from scipy.spatial import cKDTree
from scipy.sparse.csgraph import connected_components

R5 = 5.0 ** 0.5
PHI = (1.0 + R5) / 2.0
TARGET_G_FOAM = 1.0 / (4.0 * PHI ** 10)      # ~ 2.0339e-3
TARGET_RATIO  = 2.0 * PHI ** 5               # ~ 22.1803  (= ell_*/ell_P)

try:                                          # numpy>=2 renamed trapz -> trapezoid
    from numpy import trapezoid as _trapz
except ImportError:
    from numpy import trapz as _trapz


# ====================================================================================
# MPI helpers (serial when unavailable or size==1)
# ====================================================================================
def get_comm(use_mpi):
    if not use_mpi:
        return None, 0, 1
    try:
        from mpi4py import MPI
        c = MPI.COMM_WORLD
        return c, c.Get_rank(), c.Get_size()
    except Exception as e:
        sys.stderr.write("MPI requested but mpi4py unavailable (%s); serial.\n" % e)
        return None, 0, 1


# ====================================================================================
# [H1]  Icosian E8 -> H4 cut-and-project
# ====================================================================================
_GEN_CACHE = None

def _icosian_generators():
    """120 unit icosians (600-cell) as integer 8-vectors (a,b)x4, coord = (a+b*sqrt5)/4."""
    global _GEN_CACHE
    if _GEN_CACHE is not None:
        return _GEN_CACHE
    SIG, HALF, TAU = PHI / 2, 0.5, (PHI - 1) / 2          # phi/2, 1/2, phi^-1/2
    AB = {round(SIG, 9): (1, 1), round(-SIG, 9): (-1, -1),
          round(HALF, 9): (2, 0), round(-HALF, 9): (-2, 0),
          round(TAU, 9): (-1, 1), round(-TAU, 9): (1, -1),
          0.0: (0, 0), round(1.0, 9): (4, 0), round(-1.0, 9): (-4, 0)}
    # even permutations of 4 elements (A4)
    A4 = []
    for p in itertools.permutations(range(4)):
        s = 1
        for i in range(4):
            for j in range(i + 1, 4):
                if p[i] > p[j]:
                    s = -s
        if s == 1:
            A4.append(p)
    ico = set()
    for pos in range(4):                                 # 8 : (+-1,0,0,0)
        for sg in (1, -1):
            v = [0, 0, 0, 0]; v[pos] = sg; ico.add(tuple(v))
    for s in itertools.product([HALF, -HALF], repeat=4): # 16 : (+-1/2)^4
        ico.add(tuple(s))
    base = [SIG, HALF, TAU, 0.0]                          # 96 : even perms (sig,1/2,tau,0)
    for p in A4:
        for sgn in itertools.product([1, -1], repeat=3):
            t = [0, 0, 0, 0]; nz = 0
            for slot, src in enumerate(p):
                val = base[src]
                if abs(val) > 1e-9:
                    val *= sgn[nz]; nz += 1
                t[slot] = val
            ico.add(tuple(round(x, 9) for x in t))
    G = np.array([[AB[round(c, 9)][i] for c in q for i in (0, 1)] for q in sorted(ico)],
                 dtype=np.int64)
    _GEN_CACHE = G
    return G


def _emb(M, sign):
    """integer 8-vectors -> 4D float coords; sign=+1 physical, -1 internal (Galois)."""
    a = M[:, 0::2]; b = M[:, 1::2]
    return (a + sign * b * R5) / 4.0


def e8_points(N, rng):
    """Icosian H4 quasicrystal patch of >= N points (additive closure, internal window)."""
    GEN = _icosian_generators()
    rho = 4.0
    for _ in range(8):
        s = rng.normal(size=4) * (rho * 0.25)            # random internal shift -> sample
        visited = {b"\x00" * 64}
        z0 = np.zeros(8, dtype=np.int64)
        frontier = [z0]; rows = [z0]
        while frontier and len(rows) < N:
            F = np.array(frontier)
            nb = (F[:, None, :] + GEN[None, :, :]).reshape(-1, 8)
            ii = _emb(nb, -1) - s
            nb = nb[(ii ** 2).sum(1) <= rho * rho]
            newf = []
            for r in nb:
                key = r.astype(np.int16).tobytes()
                if key not in visited:
                    visited.add(key); newf.append(r); rows.append(r)
                    if len(rows) >= N:
                        break
            frontier = newf
        if len(rows) >= N:
            break
        rho *= 1.3
    M = np.array(rows)
    P = _emb(M, +1)
    # center & take the N physically-innermost (compact patch)
    P = P - P.mean(0)
    order = np.argsort((P ** 2).sum(1))
    return P[order[:N]]


def poisson_points(N, rng, dim=4):
    return rng.random((N, dim))


# ====================================================================================
# Foam graph + (weighted) Laplacian
# ====================================================================================
def build_graph(points, z, pc, rng):
    N = len(points)
    k = min(z + 1, N)
    tree = cKDTree(points)
    _, idx = tree.query(points, k=k, workers=-1)
    src = np.repeat(np.arange(N), k - 1)
    dst = idx[:, 1:].ravel()
    lo = np.minimum(src, dst); hi = np.maximum(src, dst)
    key = np.unique(lo.astype(np.int64) * N + hi)
    ei = (key // N).astype(np.int64); ej = (key % N).astype(np.int64)
    keep = rng.random(len(ei)) < pc                      # bond dilution at criticality
    ei, ej = ei[keep], ej[keep]
    if len(ei) == 0:
        return ei, ej, points[:0], np.arange(0)
    A = sp.coo_matrix((np.ones(len(ei)), (ei, ej)), shape=(N, N))
    A = (A + A.T).tocsr()
    _, lab = connected_components(A, directed=False)
    giant = np.argmax(np.bincount(lab))
    mask = lab == giant
    remap = -np.ones(N, np.int64); remap[mask] = np.arange(mask.sum())
    sel = mask[ei] & mask[ej]
    return remap[ei[sel]], remap[ej[sel]], points[mask], np.where(mask)[0]


def weighted_laplacian(ei, ej, n, w):
    W = sp.coo_matrix((w, (ei, ej)), shape=(n, n)); W = (W + W.T).tocsr()
    d = np.asarray(W.sum(1)).ravel()
    return (sp.diags(d) - W).tocsr()


# ====================================================================================
# Stochastic Lanczos Quadrature:  K(t) = Tr exp(-tL)
# ====================================================================================
def lanczos(matvec, v0, m, n):
    V = np.zeros((n, m)); a = np.zeros(m); b = np.zeros(max(m - 1, 1))
    v = v0 / np.linalg.norm(v0); V[:, 0] = v
    w = matvec(v); a[0] = v @ w; w = w - a[0] * v
    for j in range(1, m):
        w = w - V[:, :j] @ (V[:, :j].T @ w)              # full reorth
        bj = np.linalg.norm(w)
        if bj < 1e-12:
            return a[:j], b[:max(j - 1, 1)]
        b[j - 1] = bj; v = w / bj; V[:, j] = v
        w = matvec(v); a[j] = v @ w; w = w - a[j] * v - bj * V[:, j - 1]
    return a, b


def slq_heatkernel(matvec, n, t_grid, probes, m, rng, comm=None, rank=0, size=1):
    Kt = np.zeros(len(t_grid))
    p_loc = probes // size + (1 if rank < probes % size else 0)
    for _ in range(p_loc):
        zz = rng.integers(0, 2, size=n).astype(float) * 2 - 1
        a, b = lanczos(matvec, zz, min(m, n), n)
        if len(a) == 1:
            theta = a; tau = np.array([1.0])
        else:
            theta, Sv = np.linalg.eigh(
                np.diag(a) + np.diag(b[:len(a) - 1], 1) + np.diag(b[:len(a) - 1], -1))
            tau = Sv[0, :] ** 2
        Kt += np.exp(-np.outer(t_grid, theta)) @ tau
    Kt *= n / float(probes)
    if comm is not None and size > 1:
        Kt = comm.allreduce(Kt)
    return Kt


def make_matvec(L, comm, rank, size):
    n = L.shape[0]
    if size == 1:
        return (lambda x: L @ x), n
    counts = [n // size + (1 if r < n % size else 0) for r in range(size)]
    starts = np.concatenate([[0], np.cumsum(counts)])
    r0, r1 = starts[rank], starts[rank + 1]
    Lloc = L[r0:r1, :].tocsr()
    from mpi4py import MPI

    def mv(xloc):
        x = np.empty(n)
        comm.Allgatherv(np.ascontiguousarray(xloc),
                        [x, counts, starts[:-1].tolist(), MPI.DOUBLE])
        return Lloc @ x
    return mv, (r1 - r0)


# ====================================================================================
# Spectral-dimension plateau + analytic induced-gravity normalisation [H3]
# ====================================================================================
def plateau_dim(t_grid, K):
    """Diffusive spectral dimension = peak of the (smoothed) d_s(t)=-2 dlogK/dlogt curve over
       the intermediate-t window, plus the window indices of that diffusive band."""
    logt, logK = np.log(t_grid), np.log(np.clip(K, 1e-300, None))
    ds = -2.0 * np.gradient(logK, logt)
    ds_s = np.convolve(ds, np.ones(5) / 5.0, mode="same") if len(ds) >= 5 else ds
    n = len(t_grid)
    inner = np.arange(max(1, n // 6), min(n - 1, 5 * n // 6))     # drop ~a decade each end
    jpk = inner[np.argmax(ds_s[inner])]                          # diffusive peak
    half = max(2, n // 10)
    win = np.arange(max(inner[0], jpk - half), min(inner[-1], jpk + half) + 1)
    return float(np.median(ds_s[win])), win, ds


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--N", type=int, required=True)
    ap.add_argument("--seed", type=int, required=True)
    ap.add_argument("--pc", type=float, default=1.0)
    ap.add_argument("--z", type=int, default=240)
    ap.add_argument("--foam", choices=["poisson", "e8"], default="poisson")
    ap.add_argument("--probes", type=int, default=24)
    ap.add_argument("--m", type=int, default=60)
    ap.add_argument("--eps", type=float, default=0.05)
    ap.add_argument("--kfreqs", type=str, default="0.5,1.0,1.5",
                    help="comma list of conformal-probe frequencies for the k->0 extrapolation")
    ap.add_argument("--Gnorm", type=float, default=1.0,
                    help="residual scheme multiplier (analytic prefactor is built in; default 1)")
    ap.add_argument("--dfix", type=float, default=4.0,
                    help="dimension for the EH prefactor; 4.0 = the paper's PROVEN d_BS (icosian "
                         "cut-and-project, 3 estimators, no free parameter). <=0 uses measured d_s.")
    ap.add_argument("--ntimes", type=int, default=60)
    ap.add_argument("--tmin", type=float, default=1e-3)
    ap.add_argument("--tmax", type=float, default=1e3)
    ap.add_argument("--mpi", action="store_true")
    ap.add_argument("--out", type=str, default="")
    args = ap.parse_args()

    comm, rank, size = get_comm(args.mpi)
    t0 = time.time()
    rng = np.random.default_rng(args.seed * 1_000_003 + 7)

    if rank == 0:
        pts = e8_points(args.N, rng) if args.foam == "e8" else poisson_points(args.N, rng)
        ei, ej, npos, _ = build_graph(pts, args.z, args.pc, rng)
        n = int(npos.shape[0]) if npos.ndim == 2 else 0
        payload = (ei, ej, npos, n)
    else:
        payload = None
    if comm is not None and size > 1:
        payload = comm.bcast(payload, root=0)
    ei, ej, npos, n = payload

    t_grid = np.logspace(math.log10(args.tmin), math.log10(args.tmax), args.ntimes)
    res = {"N_target": args.N, "seed": args.seed, "pc": args.pc, "z": args.z,
           "foam": args.foam, "n_giant": int(n), "phi": PHI, "ranks": size,
           "target_G_foam": TARGET_G_FOAM, "target_ratio": TARGET_RATIO}
    if n < 32:
        res["status"] = "giant_too_small"
        return _emit(res, args.out, rank)

    # flat heat-kernel + diffusive spectral dimension
    L0 = weighted_laplacian(ei, ej, n, np.ones(len(ei)))
    mv0, nloc0 = make_matvec(L0, comm, rank, size)
    K0 = slq_heatkernel(mv0, n if size == 1 else nloc0, t_grid, args.probes, args.m,
                        np.random.default_rng(args.seed + 101), comm, rank, size)

    kfreqs = [float(x) for x in args.kfreqs.split(",") if x.strip()]
    perk = []   # (k, E_grad, dW, ratio=E_grad/dW)
    u = npos[:, 0]; u = (u - u.min()) / (np.ptp(u) + 1e-12)
    for kf in kfreqs:
        f = np.cos(2 * math.pi * kf * u)
        E_grad = float(((f[ei] - f[ej]) ** 2).sum())
        wp = np.exp(args.eps * (f[ei] + f[ej])); wm = np.exp(-args.eps * (f[ei] + f[ej]))
        Lp = weighted_laplacian(ei, ej, n, wp); mvp, nlp = make_matvec(Lp, comm, rank, size)
        Kp = slq_heatkernel(mvp, n if size == 1 else nlp, t_grid, args.probes, args.m,
                            np.random.default_rng(args.seed + int(kf * 1000) + 7), comm, rank, size)
        Lm = weighted_laplacian(ei, ej, n, wm); mvm, nlm = make_matvec(Lm, comm, rank, size)
        Km = slq_heatkernel(mvm, n if size == 1 else nlm, t_grid, args.probes, args.m,
                            np.random.default_rng(args.seed + int(kf * 1000) + 99), comm, rank, size)
        if rank == 0:
            R2 = (Kp + Km - 2 * K0) / (args.eps ** 2)
            _, win, _ = plateau_dim(t_grid, K0)
            dW = 0.5 * float(_trapz(R2[win], np.log(t_grid[win])))
            ratio = E_grad / dW if abs(dW) > 1e-30 else float("nan")
            perk.append((kf, E_grad, dW, ratio))

    if rank == 0:
        ds, win, ds_curve = plateau_dim(t_grid, K0)
        d_eff = args.dfix if args.dfix > 0 else ds       # proven d_BS=4 (cut-and-project)
        pref = (d_eff - 1.0) * (d_eff - 2.0) / (8.0 * math.pi)    # analytic [H3] prefactor
        # k->0 extrapolation: 1/ratio = E_grad/... -> A + B k^2 (EH + conformal anomaly)
        ks = np.array([p[0] for p in perk]); inv = np.array([1.0 / p[3] if p[3] else np.nan for p in perk])
        good = np.isfinite(inv)
        if good.sum() >= 2:
            A = np.vstack([np.ones(good.sum()), ks[good] ** 2]).T
            coef = np.linalg.lstsq(A, inv[good], rcond=None)[0]
            ratio0 = 1.0 / coef[0] if coef[0] != 0 else float("nan")   # k->0
        else:
            ratio0 = perk[0][3] if perk else float("nan")
        G_foam = args.Gnorm * pref * ratio0
        # d_BS=4 is proven; the measured heat-kernel d_s is only a numerical consistency check
        status = "ok" if abs(ds - d_eff) < 1.0 else "ok_dscheck_off(meas=%.2f)" % ds
        res.update({
            "status": status,
            "d_eff_prefactor": d_eff,
            "spectral_dim_measured": ds,
            "spectral_dim_curve": ds_curve.tolist(),
            "t_grid": t_grid.tolist(),
            "K_flat": K0.tolist(),
            "prefactor": pref,
            "per_k": [{"k": p[0], "E_grad": p[1], "Delta_W": p[2], "ratio": p[3]} for p in perk],
            "ratio_k0": ratio0,
            "G_foam_normed": G_foam,
            "Gnorm": args.Gnorm,
            "peak_rss_mb": round(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 1024.0, 1),
            "wall_s": round(time.time() - t0, 2),
        })
        _emit(res, args.out, rank)


def _emit(res, out, rank):
    if rank != 0:
        return
    line = json.dumps(res)
    if out:
        open(out, "w").write(line + "\n")
    else:
        print(line)


if __name__ == "__main__":
    main()
